---
deployment:
    tasks:
        - export DEPLOYPATH=/home/ajpetrte/public_html/mitsubishicarworld.com.ph/
        - /bin/mkdir -p $DEPLOYPATH
        - /bin/rm -rf $DEPLOYPATH*
        - /bin/cp -R $REPOPATH/dist/. $DEPLOYPATH
